[build]
builder = "nixpacks"
buildCommand = "cd PanelaControl/PanelaControl && npm install && npm run build"

[deploy]
startCommand = "cd PanelaControl/PanelaControl && npm start"
healthcheckTimeout = 100
restartPolicyType = "always"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production"